### ISSUE TITLE
Rename made entire addon non-functional

### ISSUE THREAD

**Issue by Cirrial** [phnix-dev/kenney-assets-godot-plugin#1]
Every scene and script is referencing the folder "kenney_assets_viewer" which doesn't exist in the addon code. As a result, the addon doesn't work when installed.

**Comment by Cirrial** [comment]
never mind, this addon doesn't seem to be supported anymore

**Comment by phnix-dev** [comment]
Thanks for the bug report, I will get it fixed!

**Comment by phnix-dev** [comment]
It is fixed! 👍
